name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Adicione aqui outros passos relevantes para seu projeto.
      # Se você não precisar instalar dependências com npm, remova essa etapa.
      # Exemplo:
      # - name: Install dependencies
      #   run: your-command-to-install-dependencies

      - name: Run a sample script
        run: echo "Hello, World!"

      # Adicione outras etapas que sejam relevantes para seu fluxo de trabalho
